### PR TITLE
default `_` in the first location

### PR DESCRIPTION
**Pull request by kongdd**
This commit solved the issue #22

### CODE REVIEW

**Comment by oxinabox** [comment]
see comment in #22
thank you for your interest, but this is not a feature we want.

**Comment by kongdd** [comment]
Thank u. 

I am wondering whether can I include Pipe in my package?
<https://github.com/jl-spatial/Ipaper.jl/blob/master/src/Pipe.jl>

**Comment by oxinabox** [comment]
yes, it is MIT licensed

**Comment by kongdd** [comment]
Thank u

**Pull request closed without merging**
